version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./src/main/resources/static/db-navigation/schema.sql:/docker-entrypoint-initdb.d/schema.sql


  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8189
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    ports:
      - "8189:8189"  
    depends_on:
      - postgres


