server:
    port: 8189
    servlet:
        context-path: /api
jwt:
    lifetime: 10m
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123
logging:
    pattern:
        file:  "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file:
        name: src/main/resources/logs/logs-debug.log
    level:
        root: info

